# Importando Bibliotecas

In [65]:
import numpy as np
import random

# Gerando a tabela de distâncias

In [66]:

dists = np.zeros((6,6), dtype=int)
lim = 0 #criação da variável auxiliar
for i in range(0, dists.shape[0]):
    lim += 1
    j = 0
    while j < lim:
        if i != j:
            x = random.randint(1,100)
            dists[i][j] = x
            dists[j][i] = x
        j += 1
print(dists) 

#O array de 2 dimensões representa uma tabela de distâncias da maneira mais fidedigna possível, pois a posição i,j é a mesma que 
#j,i. E também se i e j estão na mesma posição, seu valor é 0.

[[ 0 26 14 22 35  5]
 [26  0 88 14 69 26]
 [14 88  0  1 82 84]
 [22 14  1  0 13 70]
 [35 69 82 13  0 28]
 [ 5 26 84 70 28  0]]


Iniciando os indivíduos

In [67]:
num_individuos = 20
numeros = np.array([0,1,2,3,4,5,0])
populacao_inicial = np.zeros((num_individuos,len(numeros)),dtype=int)
for i in range (num_individuos):
    np.random.shuffle(numeros)
    populacao_inicial[i] = numeros
    
    



# Funções 

Funções de Fitness

In [68]:
def fitness (ind):
    f = 0
    for x in range(len(ind)-1):
        i,j = ind[x],ind[x+1]
        f+= dists[i][j]
        
    if(ind[0]!=0):
        f+= 300
        
    if ind[len(ind)-1] != 0:
        f+= 300
        
    return 1200-f
        
def retorna_fitness(populacao):
    fit = []
    for i in range(num_individuos):
        f = fitness(populacao[i])
        fit.append(f)
    return fit

Torneio

In [69]:
def selecao_torneio(fitnesses):
    pai1 = -1
    pai2 = -1
    while pai1 == pai2:
        sorteados = random.sample(range(0, num_individuos), 2)
        if fitnesses[sorteados[0]] >= fitnesses[sorteados[1]]:
            pai1 = sorteados[0]
        else:
            pai1 = sorteados[1]

        sorteados = random.sample(range(0, num_individuos), 2)
        if fitnesses[sorteados[0]] > fitnesses[sorteados[1]]:
            pai2 = sorteados[0]
        else:
            pai2 = sorteados[1]  
        
    return pai1,pai2      

In [70]:
def cruzamento(ids,populacao):
    numeros = np.array([0,1,2,3,4,5,0])
    ponto = random.randint(0, len(numeros)-0)
    pai1 = populacao[ids[0]]
    pai2 = populacao[ids[1]]
    
    filho1 = np.concatenate([pai1[:ponto],pai2[ponto:]])
    filho2 = np.concatenate([pai2[:ponto],pai1[ponto:]])

    if len(np.unique(filho1)) != 6: #verificando se existem 6 números únicos no indivíduo
        dif1 = np.setdiff1d(numeros, filho1)
        balancear(filho1,dif1)
    
    if len(np.unique(filho2)) != 6:
        dif2 = np.setdiff1d(numeros, filho2)
        balancear(filho2,dif2)
    
        
        
    return filho1,filho2

Essa função irá garantir que o array tenha valores diferentes, pois um indivíduo com valores repetidos é infactível.


In [71]:
def balancear(filho,dif):
    if (random.randint(0,100)) < 50:
        np.random.shuffle(dif)
    i = 0
    repetidos = []
    while len(dif) != 0:
        if filho[i] not in repetidos:
            repetidos.append(filho[i])
        else:
            filho[i] = dif[0]
            dif = np.delete(dif,0)
        i+= 1
    return filho

In [72]:
def mutacao(filhos,taxa):
    for i in range(len(filhos)):
        if random.random() < taxa:
            pos1 = random.randint(0,len(numeros)-1)
            pos2 = random.randint(0,len(numeros)-1)
            filhos[i][pos1],filhos[i][pos2] = filhos[i][pos2],filhos[i][pos1] #invertendo duas cidades dos filhos
            
        
    return filhos 

In [73]:
def elitismo(fitnesses):

    id1 = fitnesses.index(max(fitnesses))

    fitnesses.pop(id1)
    id2 = fitnesses.index(max(fitnesses))

    return id1,id2

# Programa Principal

In [74]:
num_geracoes = 500

for it in range(num_geracoes):
    nova_populacao = np.zeros((num_individuos,len(numeros)), dtype=int)
    fit = retorna_fitness(populacao_inicial)
    id_melhor = fit.index(max(fit))

    print(f"Geração {it}. Melhor escolha: {populacao_inicial[id_melhor]}, Fitness: {fit[id_melhor]}")
    
    elite = elitismo(fit.copy()) 
    nova_populacao[0] = populacao_inicial[elite[0]]
    nova_populacao[1] = populacao_inicial[elite[1]]
    
    num_filhos = 2
    
    while num_filhos < num_individuos:

        ind_vencedores = selecao_torneio(fit)

        filhos = cruzamento(ind_vencedores,populacao_inicial)

        filhos = mutacao(filhos,0.5)

        nova_populacao[num_filhos] = filhos[0]
        nova_populacao[num_filhos+1] = filhos[1]

        num_filhos = num_filhos + 2

    populacao_inicial = nova_populacao.copy()

Geração 0. Melhor escolha: [2 3 4 1 0 5 0], Fitness: 781
Geração 1. Melhor escolha: [0 4 3 2 1 5 0], Fitness: 1032
Geração 2. Melhor escolha: [0 4 3 2 1 5 0], Fitness: 1032
Geração 3. Melhor escolha: [0 4 3 2 1 5 0], Fitness: 1032
Geração 4. Melhor escolha: [0 4 3 2 1 5 0], Fitness: 1032
Geração 5. Melhor escolha: [0 4 3 2 1 5 0], Fitness: 1032
Geração 6. Melhor escolha: [0 4 2 3 1 5 0], Fitness: 1037
Geração 7. Melhor escolha: [0 2 3 4 1 5 0], Fitness: 1072
Geração 8. Melhor escolha: [0 2 3 4 1 5 0], Fitness: 1072
Geração 9. Melhor escolha: [0 2 3 4 1 5 0], Fitness: 1072
Geração 10. Melhor escolha: [0 2 3 4 1 5 0], Fitness: 1072
Geração 11. Melhor escolha: [0 2 3 4 1 5 0], Fitness: 1072
Geração 12. Melhor escolha: [0 2 3 4 1 5 0], Fitness: 1072
Geração 13. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 14. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 15. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 16. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 

Geração 287. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 288. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 289. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 290. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 291. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 292. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 293. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 294. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 295. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 296. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 297. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 298. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 299. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 300. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 301. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 302. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 303. Melhor escolha: [0 2 3 4 5 

Geração 427. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 428. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 429. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 430. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 431. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 432. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 433. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 434. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 435. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 436. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 437. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 438. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 439. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 440. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 441. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 442. Melhor escolha: [0 2 3 4 5 1 0], Fitness: 1092
Geração 443. Melhor escolha: [0 2 3 4 5 